server:
  port: '9090'

spring:
  datasource:
    username: saleem8396
    url: jdbc:mysql://localhost:3306/saleem8396_demo
    driverClassName: com.mysql.cj.jdbc.Driver
    password: saleem8396@098
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  security:
    user:
      name: saleem
      password: saleem
      role: Admin